user-message: "WARNING: This stack project is generated."

compiler: ghc-9.8.1
compiler-check:
  match-exact

resolver: ghc-9.8.1

# We have 1 packages.
packages:
  - ./.

# We have 0 source packages listed in this order:
#   * external 0
#   * internal 0
#   * external forks 0
#   * internal forks 0
extra-deps:

  # Source Packages, external (3rd party).

  # Source Packages, internal to this organisation (private and public).

  # Source Packages, external (3rd party) forks of other repositories.
  # Can we help upstream?

  # Source Packages, internal forks of other repositories.
  # Can we upstream and unfork?

  # Package versions for published packages either not on Stackage or
  # not matching the version on Stackage for the resolver we use.
  # These package-version extra dependencies are equivalent to cabal constraints.
  - base-4.19.0.0
  - binary-0.8.9.1
  - bytestring-0.12.0.2
  - containers-0.6.8
  - directory-1.3.8.1
  - filepath-1.4.100.4
  - ghc-prim-0.11.0
  - haskeline-0.8.2.1
  - mtl-2.3.1
  - parsec-3.1.17.0
  - process-1.6.18.0
  - template-haskell-2.21.0.0
  - time-1.12.2
  - HTTP-4000.4.1
  - SHA-1.6.4.4
  - ansi-terminal-1.0
  - ansi-wl-pprint-0.6.9
  - edit-distance-0.2.2.1
  - file-embed-0.0.15.0
  - filelock-0.1.1.7
  - http-client-0.7.15
  - http-client-tls-0.3.6.3
  - http-types-0.12.3
  - language-glsl-0.3.0
  - network-3.1.4.0
  - raw-strings-qq-1.1
  - scientific-0.3.7.0
  - snap-core-1.0.5.1
  - snap-server-1.1.2.1
  - unordered-containers-0.2.19.1
  - utf8-string-1.0.2
  - vector-0.13.1.0
  - zip-archive-0.4.3
  - network-uri-2.6.4.2
  - ansi-terminal-types-0.11.5
  - colour-2.3.6
  - random-1.2.1.1
  - async-2.2.5
  - base64-bytestring-1.2.1.0
  - blaze-builder-0.4.2.3
  - case-insensitive-1.2.1.0
  - cookie-0.4.6
  - iproute-1.7.12
  - mime-types-0.1.2.0
  - streaming-commons-0.2.2.6
  - hashable-1.4.3.0
  - data-default-class-0.1.2.0
  - crypton-0.34
  - crypton-connection-0.3.1
  - memory-0.18.0
  - tls-1.9.0
  - basement-0.0.16
  - crypton-x509-1.7.6
  - crypton-x509-store-1.6.9
  - crypton-x509-system-1.6.7
  - crypton-x509-validation-1.6.12
  - socks-0.6.1
  - asn1-encoding-0.9.6
  - asn1-parse-0.9.5
  - asn1-types-0.3.4
  - hourglass-0.2.12
  - pem-0.2.4
  - appar-0.1.8
  - byteorder-1.0.4
  - prettyclass-1.0.0.0
  - th-compat-0.1.4
  - splitmix-0.1.0.5
  - integer-logarithms-1.0.3.1
  - primitive-0.9.0.0
  - HUnit-1.6.2.0
  - attoparsec-0.14.4
  - bytestring-builder-0.10.8.2.0
  - io-streams-1.5.2.2
  - lifted-base-0.2.3.12
  - monad-control-1.0.3.1
  - old-locale-1.0.0.7
  - readable-0.3.1@rev:1
  - regex-posix-0.96.0.1
  - transformers-base-0.4.6
  - unix-compat-0.7
  - call-stack-0.4.0
  - zlib-bindings-0.1.1.5
  - transformers-compat-0.7.2
  - regex-base-0.94.0.2
  - clock-0.8.4
  - io-streams-haproxy-1.0.1.0
  - cereal-0.5.8.3
  - zlib-0.6.3.0
  - unix-time-0.4.11
  - base-orphans-0.9.1
  - old-time-1.1.0.3
  - vector-stream-0.1.0.0
  - digest-0.0.1.7
